### ISSUE TITLE
Caddy fails to build

### ISSUE THREAD

**Issue by miguemely** [caddyserver/ntlm-transport#1]
When attempting to build Caddy v2, I get the following error:
# github.com/caddyserver/ntlm-transport
/go/pkg/mod/github.com/caddyserver/ntlm-transport@v0.1.0/ntlm.go:161:48: not enough arguments in call to n.HTTPTransport.NewTransport
        have ()
        want (caddy.Context)

**Comment by mholt** [comment]
Oh -- you need to use the latest commit in this repo, the latest tag won't work.

I'll push a new tag in a bit.

Edit: fixed in v0.1.1

**Comment by miguemely** [comment]
Sounds like a whoops. Thanks! 

Also, obligiatory first.
