### ISSUE TITLE
ntlm-transport@v0.1.1/ntlm.go:111:18: n.HTTPTransport.SetScheme undefined

### ISSUE THREAD

**Issue by roukmoute** [caddyserver/ntlm-transport#2]
I've got this error :  

```sh
ntlm-transport@v0.1.1/ntlm.go:111:18: n.HTTPTransport.SetScheme undefined (type *"github.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy".HTTPTransport has no field or method SetScheme)
```

When I try to install [nginx-adapter](https://github.com/caddyserver/nginx-adapter)

This ticket is a part from: https://github.com/caddyserver/nginx-adapter/issues/25#issuecomment-1182756531

**Comment by mholt** [comment]
Thanks for the report. Fixed in https://github.com/caddyserver/ntlm-transport/commit/abdbda2c2e6f25b3e97ba408a7c6d2b78abacd6e.
