### ISSUE TITLE
Update to lastest caddy version

### ISSUE THREAD

**Issue by Nonobis** [caddyserver/ntlm-transport#7]
Hello, 

Could you update the plugin for using the lastest caddy version ?
Thank you

**Comment by mholt** [comment]
Sure -- I'm pretty busy this week though, however I could click a button to merge a PR if you're interested in that!

**Comment by Nonobis** [comment]
i don't known how to update the checksum in go. Where to find information

**Comment by mholt** [comment]
No worries; just run `go get github.com/caddyserver/caddy/v2@latest` and then run `go mod tidy`. It should update go.mod and go.sum.

**Comment by Nonobis** [comment]
i have installed go on windows, forked repo and tryed the command but it's not working .. do you have a read me somewhere for updating this plugin ?

**Comment by mholt** [comment]
Sorry for the delay -- had some weird issues with GH notifications, then got backlogged... anyway, finally catching up and just pushed https://github.com/caddyserver/ntlm-transport/commit/e0c1e46a30093fa243d06a83964da5573ee6a51f.
